# Generated by Django 3.2 on 2021-05-06 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_sale_total_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='saleman',
            new_name='salesman',
        ),
    ]
